name: check code quality
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.0.6'
      - name: Install packages
        run: flutter pub get
      - name: Formatting
        run: dart format --set-exit-if-changed lib
      - name: Linting
        run: flutter analyze
